spring:
  application:
    name: soa
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0                   # 将采样比例设置为1.0，也就是全部都需要。默认是0.1
  zipkin:
    base-url: http://localhost:9411/     # 指定了 Zipkin 服务器的地址

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
feign:
  hystrix:
    enabled: true

study:
  oauth2:
    soa:
      client_id: WttToLN6Lt6lwerrfT5b
      client_secret: oLN6Ltyshihx5g9btschbI8Puc
      grant_type: password
      scope: STUDY_SOA

rocketmq:
  producer:
    groupName: testGroup
    namesrvAddr: 192.168.146.128:9876
    instanceName: testProducer
    topic: topic2020
    tag: test
    maxMessageSize: 131072
    sendMsgTimeout: 10000

  consumer:
    groupName: testGroup
    namesrvAddr: 192.168.146.128:9876
    topic: topic2020
    tag: test
    consumeThreadMin: 20
    consumeThreadMax: 64