server:
  port: 8091
spring:
  application:
    name: auth

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

study:
  oauth:
    clients:
      # SOA
      - clientName: STUDY_SOA
        clientId: WttToLN6Lt6lwerrfT5b
        clientSecret: oLN6Ltyshihx5g9btschbI8Puc
        scope: STUDY_SOA
        resourceIds:
          - AUTH-RESOURCE-SERVER
        authorizedGrantTypes:
          - password
          - refresh_token
        authorities:
          - ROLE_SOA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/